export const AUTH_REGISTRATION_REQUEST = "auth/AUTH_REGISTRATION_REQUEST";
export const AUTH_REGISTRATION_SUCCESS = "auth/AUTH_REGISTRATION_SUCCESS";
export const AUTH_REGISTRATION_FAILURE = "auth/AUTH_REGISTRATION_FAILURE";

export const AUTH_LOGIN_REQUEST = "auth/AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "auth/AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "auth/AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "auth/AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "auth/AUTH_LOGOUT_SUCCESS";

export const AUTH_JWT_REQUEST = "auth/AUTH_JWT_REQUEST";
export const AUTH_JWT_SUCCESS = "auth/AUTH_JWT_SUCCESS";
export const AUTH_JWT_FAILURE = "auth/AUTH_JWT_FAILURE";

export const AUTH_IS_FETCHING = "auth/duck/types/AUTH_IS_FETCHING";
export const AUTH_IS_FINISHED = "auth/duck/types/AUTH_IS_FINISHED";