export const SOCKET_ACTION_EMIT = "socket/SOCKET_ACTION_EMIT";
export const SOCKET_DISCONNECTED = "socket/SOCKET_DISCONNECTED";
export const SOCKET_CONNECTING = "socket/SOCKET_CONNECTING";
export const SOCKET_CONNECTED = "socket/SOCKET_CONNECTED";
export const SOCKET_DISCONNECT = "socket/SOCKET_DISCONNECT";
export const SOCKET_NAMESPACES_CONNECTED = "socket/SOCKET_NAMESPACES_CONNECTED";
export const CONNECT_ALL_RECEIVE = "socket/CONNECT_ALL_RECEIVE";