export const LIST_CREATE_REQUEST = "lists/LIST_CREATE_REQUEST";
export const LIST_CREATE_SUCCESS = "lists/LIST_CREATE_SUCCESS";
export const LIST_CREATE_FAILURE = "lists/LIST_CREATE_FAILURE";
export const LIST_CREATE_RECEIVE = "lists/LIST_CREATE_RECEIVE";

export const LIST_UPDATE_REQUEST = "lists/LIST_UPDATE_REQUEST";
export const LIST_UPDATE_SUCCESS = "lists/LIST_UPDATE_SUCCESS";
export const LIST_UPDATE_FAILURE = "lists/LIST_UPDATE_FAILURE";
export const LIST_UPDATE_RECEIVE = "lists/LIST_UPDATE_RECEIVE";

export const LIST_DELETE_REQUEST = "lists/LIST_DELETE_REQUEST";
export const LIST_DELETE_SUCCESS = "lists/LIST_DELETE_SUCCESS";
export const LIST_DELETE_FAILURE = "lists/LIST_DELETE_FAILURE";
export const LIST_DELETE_RECEIVE = "lists/LIST_DELETE_RECEIVE";

export const LIST_ADD = "lists/LIST_ADD";
export const LIST_REMOVE = "lists/LIST_REMOVE";
export const LIST_EDIT = "lists/LIST_EDIT";