export const USER_LOAD_INITIAL_DATA_REQUEST = "user/duck/types/USER_LOAD_INITIAL_DATA_REQUEST";
export const USER_LOAD_INITIAL_DATA_SUCCESS = "user/duck/types/USER_LOAD_INITIAL_DATA_SUCCESS";
export const USER_LOAD_INITIAL_DATA_FAILURE = "user/duck/types/USER_LOAD_INITIAL_DATA_FAILURE";