export const CREATE_TASK_REQUEST = 'tasks/CREATE_TASK_REQUEST_EVERY';
export const CREATE_TASK_SUCCESS = 'tasks/CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'tasks/CREATE_TASK_FAILURE';
export const GET_TASKS_REQUEST = 'tasks/GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'tasks/GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'tasks/GET_TASKS_FAILURE';
