const SIGNUP_REQUEST = 'signup/SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'signup/SIGNUP_SUCCESS';
const SIGNUP_FAILURE = 'signup/SIGNUP_FAILURE';

export {SIGNUP_REQUEST, SIGNUP_SUCCESS, SIGNUP_FAILURE};
