export const CHANNEL_CREATE_REQUEST = "channel/duck/types/CHANNEL_CREATE_REQUEST";
export const CHANNEL_CREATE_SUCCESS = "channel/duck/types/CHANNEL_CREATE_SUCCESS";
export const CHANNEL_CREATE_FAILURE = "channel/duck/types/CHANNEL_CREATE_FAILURE";
export const CHANNEL_CREATE_SEND = "channel/CHANNEL_CREATE_SEND";
export const CHANNEL_CREATE_RECEIVE = "channel/CHANNEL_CREATE_RECEIVE";


export const CHANNEL_UPDATE_REQUEST = "channel/duck/types/CHANNEL_UPDATE_REQUEST";
export const CHANNEL_UPDATE_SUCCESS = "channel/duck/types/CHANNEL_UPDATE_SUCCESS";
export const CHANNEL_UPDATE_FAILURE = "channel/duck/types/CHANNEL_UPDATE_FAILURE";
export const CHANNEL_UPDATE_RECEIVE = "channel/CHANNEL_UPDATE_RECEIVE";

export const CHANNEL_DELETE_REQUEST = "channel/duck/types/CHANNEL_DELETE_REQUEST";
export const CHANNEL_DELETE_SUCCESS = "channel/duck/types/CHANNEL_DELETE_SUCCESS";
export const CHANNEL_DELETE_FAILURE = "channel/duck/types/CHANNEL_DELETE_FAILURE";
export const CHANNEL_DELETE_RECEIVE = "channel/CHANNEL_DELETE_RECEIVE";
export const CHANNEL_DELETE = "channel/CHANNEL_DELETE";

export const CHANNEL_LIST_CREATE_REQUEST = "channel/CHANNEL_LIST_CREATE_REQUEST";
export const CHANNEL_LIST_CREATE_SUCCESS = "channel/CHANNEL_LIST_CREATE_SUCCESS";
export const CHANNEL_LIST_CREATE_FAILURE = "channel/CHANNEL_LIST_CREATE_FAILURE";

export const CHANNEL_SELECT = "channel/duck/types/CHANNEL_SELECT";
export const CHANNEL_CONNECT_SEND = "channel/CHANNEL_CONNECT_SEND";
export const CHANNEL_CONNECT_RECEIVE = "channel/CHANNEL_CONNECT_RECEIVE";

export const CHANNEL_ADD = "channel/CHANNEL_ADD";
export const CHANNEL_REMOVE = "channel/CHANNEL_REMOVE";
export const CHANNEL_EDIT = "channel/CHANNEL_EDIT";

export const CHANNELS_REMOVE = "channels/CHANNELS_REMOVE";