export const UI_MODAL_ADD = "ui/UI_MODAL_ADD";
export const UI_MODAL_REMOVE = "ui/UI_MODAL_REMOVE";
export const UI_MODAL_REMOVE_ESCAPE = "ui/UI_MODAL_REMOVE_ESCAPE";

export const UI_TOAST_CREATE = "ui/UI_TOAST_CREATE";
export const UI_TOAST_ADD = "ui/UI_TOAST_ADD";
export const UI_TOAST_REMOVE = "ui/UI_TOAST_REMOVE";

export const UI_FETCHING_ADD = "ui/UI_FETCHING_ADD";
export const UI_FETCHING_REMOVE = "ui/UI_FETCHING_REMOVE";

export const UI_SIDE_MENU_TOGGLE = "ui/SIDE_MENU_TOGGLE";

export const UI_DROPDOWN_ADD = "ui/UI_DROPDOWN_ADD";
export const UI_DROPDOWN_REMOVE = "ui/UI_DROPDOWN_REMOVE";

export const UI_PORTAL_ADD = "ui/UI_PORTAL_ADD";
export const UI_PORTAL_REMOVE = "ui/UI_PORTAL_REMOVE";
export const UI_PORTAL_REMOVE_ESCAPE = "ui/UI_PORTAL_REMOVE_ESCAPE";