export const MEMBER_JOIN = "member/MEMBER_JOIN";

export const MEMBER_CHANNEL_JOIN_RECEIVE = "member/MEMBER_CHANNEL_JOIN_RECEIVE";
export const MEMBER_CHANNEL_LEAVE_RECEIVE = "member/MEMBER_CHANNEL_LEAVE_RECEIVE";
export const MEMBER_GROUP_JOIN_RECEIVE = "member/MEMBER_GROUP_JOIN_RECEIVE";
export const MEMBER_GROUP_LEAVE_RECEIVE = "member/MEMBER_GROUP_LEAVE_RECEIVE";
export const MEMBER_NEW_RECEIVE = "member/MEMBER_NEW_RECEIVE";

export const MEMBER_TYPING_START = "members/MEMBER_TYPING_START";
export const MEMBER_TYPING_STOP = "members/MEMBER_TYPING_STOP";
export const MEMBER_TYPING_START_RECEIVE = "members/MEMBER_TYPING_START_RECEIVE";
export const MEMBER_TYPING_STOP_RECEIVE = "members/MEMBER_TYPING_STOP_RECEIVE";