export const MEMBER_JOIN = "member/MEMBER_JOIN";

export const MEMBER_CHANNEL_JOIN_RECEIVE = "member/MEMBER_CHANNEL_JOIN_RECEIVE";
export const MEMBER_CHANNEL_LEAVE_RECEIVE = "member/MEMBER_CHANNEL_LEAVE_RECEIVE";
export const MEMBER_GROUP_JOIN_RECEIVE = "member/MEMBER_GROUP_JOIN_RECEIVE";
export const MEMBER_GROUP_LEAVE_RECEIVE = "member/MEMBER_GROUP_LEAVE_RECEIVE";
export const MEMBER_NEW_RECEIVE = "member/MEMBER_NEW_RECEIVE";