export const CHAT_MESSAGE_SEND_REQUEST = "chat/duck";
export const CHAT_MESSAGE_SEND_SUCCESS = "";
export const CHAT_MESSAGE_SEND_FAILURE = "";
export const CHAT_MESSAGE_SEND = "chat/CHAT_MESSAGE_SEND";

export const CHAT_TYPING_REQUEST = "chat/CHAT_TYPING_REQUEST";
export const CHAT_TYPING_START = "chat/CHAT_TYPING_START";
export const CHAT_TYPING_STOP = "chat/CHAT_TYPING_STOP";

export const CHAT_TYPING_START_RECEIVE = "chat/CHAT_TYPING_START_RECEIVE";
export const CHAT_TYPING_STOP_RECEIVE = "chat/CHAT_TYPING_STOP_RECEIVE";

export const CHAT_MESSAGE_RECEIVE = "chat/CHAT_MESSAGE_RECEIVE";
