export const CREATE_LIST_REQUEST = 'lists/CREATE_LIST_REQUEST_EVERY';
export const CREATE_LIST_SUCCESS = 'lists/CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'lists/CREATE_LIST_FAILURE';
export const GET_LISTS_REQUEST = 'lists/GET_LISTS_REQUEST_EVERY';
export const GET_LISTS_SUCCESS = 'lists/GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'lists/GET_LISTS_FAILURE';
