export const MODAL_CHANNEL_CREATE = "CHANNEL_CREATE";
export const MODAL_CHANNEL_SETTINGS = "CHANNEL_SETTINGS";
export const MODAL_GROUP_CREATE_OR_JOIN = "GROUP_CREATE_OR_JOIN";
export const MODAL_GROUP_SETTINGS = "GROUP_SETTINGS";
export const MODAL_GROUP_INVITE = "GROUP_INVITE";
export const MODAL_TASK_EDIT = "TASK_EDIT";
export const MODAL_TASK_DROPDOWN = "TASK_DROPDOWN";
export const MODAL_USER_SETTINGS = "USER_SETTINGS";
export const MODAL_CONNECTION = "SOCKET_CONNECTION";
export const MODAL_CHANNEL_INVITE = "CHANNEL_INVITE";

export const DROPDOWN_LIST = "LIST_DROPDOWN";
export const DROPDOWN_TASK = "TASK_DROPDOWN";
export const POPOVER_TASK_MOVE = "POPOVER_TASK_MOVE";
export const PORTAL_TASK_OVERLAY = "TASK_OVERLAY";